[build-all] Implements build-all script.

diff --git a/build-all b/build-all
--- a/build-all
+++ b/build-all
@@ -14,7 +14,38 @@ do
 
   # skip comments and empty lines
   is_comment_or_empty $line && continue
-  info $line
+  count=$(echo "${line}" | awk -F":" '{print NF-1}')
+  [[ $count -ne 1 && $count -ne 3 ]] \
+    && warn "ERROR: Wrong format!" \
+    && echo "Ignoring line ${line_nr}: ${line}" \
+    && continue
+
+  name=${line%%:*}
+  dest_folder=${line#*:}
+  src_folder="${SRC_DIR}/${name}"
+
+  if [ $count -ne 1 ]
+    then
+      build=${dest_folder#*:}
+      build=${build%%:*}
+      {
+        pushd $src_folder \
+          && eval $build \
+          && popd
+      } || {
+        warn "ERROR: Could not evaluate build command" \
+          && echo "Ignoring line ${line_nr}: ${line}" \
+          && continue
+      }
+      dist=${dest_folder##*:}
+      dest_folder=${dest_folder%%:*}
+      src_folder="${src_folder}/${dist}"
+  fi
+
+  dest_folder="wp-content/${dest_folder}/${name}"
+
+  cp -rf $src_folder/. $dest_folder \
+    || warn "ERROR: Could not copy files for ${name}"
 
 done < "$BUILD_CONF"
 
